name: npm audit

on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"
  # schedule:
  #   - cron: '0 10 * * *'

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    concurrency:
      group: npm-audit-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Cache node modules
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-.-node-modules-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-.-node-modules-

      - name: install dependencies
        run: npm install
      - uses: oke-py/npm-audit-action@828ccb3b0710dfb351b6e9aaadec963c6953cacf # v4.0.2
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_labels: vulnerability,test
          dedupe_issues: true
