name: npm audit

on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"
  # schedule:
  #   - cron: '0 10 * * *'

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    concurrency:
      group: npm-audit-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Cache node modules
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-.-node-modules-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-.-node-modules-

      - name: install dependencies
        run: npm install
      - uses: oke-py/npm-audit-action@f02a3cf15e7a1860efac849dd45126f9c2cafe4f # v4.0.1
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_labels: vulnerability,test
          dedupe_issues: true
