name: Prettier

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: prettier-${{ github.ref }}
  cancel-in-progress: false

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-.-node-modules-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-.-node-modules-

      - name: Install Prettier
        run: npm install --no-save prettier

      - name: Prettify code
        uses: creyD/prettier_action@8c18391fdc98ed0d884c6345f03975edac71b8f0 # v4.6
        with:
          prettier_options: --check **/*.{js,md,css,html}
        continue-on-error: true
