name: Spellcheck Action
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
concurrency:
  group: spellcheck-${{ github.ref }}
  cancel-in-progress: false
permissions:
  contents: read

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: rojopolis/spellcheck-github-actions@e3cd8e9aec4587ec73bc0e60745aafd45c37aa2e # 0.60.0
        name: Spellcheck
        continue-on-error: true
        with:
          config_path: .github/.spellcheck.yml
          output_file: spellcheck-output.txt
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: ${{ !cancelled() }}
        with:
          name: Spellcheck Output
          path: spellcheck-output.txt
