name: StyleLint

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: stylelint-${{ github.ref }}
  cancel-in-progress: false

jobs:
  linters:
    name: stylelint
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout Repo Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run StyleLint
        uses: actions-hub/stylelint@79a72921dfce2e51791be2df406f0c103fb47553 # v1.1.6
        env:
          PATTERN: "./*.css ./**/*.css"
        continue-on-error: true # Continue even if this step fails
